

```{r}
##### LOAD PACKAGES
library("sas7bdat")
library("dplyr")
library("tidyverse")
library("plyr")
library("haven")

##### LOAD DATASET
PFAS_X <- read.sas7bdat("C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/ja_080621.sas7bdat")

ls(PFAS_X)

```

```{r}
##### DROP UNNECESSARY VARIABLES
PFAS_X <- subset(PFAS_X, select = c(aid, PFOS, Et_PFOSA_AcOH, parity_d, PFOSA, coll_grad, highbp_mom_epi_epia_d,
                                    PFDeA, htn_rx_preg, Me_PFOSA_AcOH2, PFHxS, t1diab_mom_epi_epia_d,
                                    income_hh_epq_epqa_d, PFNA2, race2_mom_epi_epia_d, t2diab_mom_epi_epia_d, 
                                    bmi_mom_prepreg_d, PFOA, smokpreg_final_d, vig_pre_d, g_age_days_COLL_D_BLD1, mod_pre_d))

##### LOG TRANSFORM PFAS FOR LATER PCA ANALYSES
PFAS_X$LNPFOS <- log(PFAS_X$PFOS)
PFAS_X$LNPFOA <- log(PFAS_X$PFOA)
#PFAS_X$LNPFOSA <- log(PFAS_X$PFOSA)
PFAS_X$LNPFNA2 <- log(PFAS_X$PFNA2)
PFAS_X$LNPFHxS <- log(PFAS_X$PFHxS)
#PFAS_X$LNPFDeA <- log(PFAS_X$PFDeA)
PFAS_X$LNME_PFOSA <- log(PFAS_X$Me_PFOSA_AcOH2)
PFAS_X$LNET_PFOSA <- log(PFAS_X$Et_PFOSA_AcOH)

```


```{r}
##### IMPUTE MISSING DEMOGRAPHIC DATA 

PFAS_X$income_hh_epq_epqa_d [is.na(PFAS_X$income_hh_epq_epqa_d)] <- 1
PFAS_X$mod_pre_d [is.na(PFAS_X$mod_pre_d)] <- mean(PFAS_X$mod_pre_d, na.rm = T)
PFAS_X$vig_pre_d [is.na(PFAS_X$vig_pre_d)] <- mean(PFAS_X$vig_pre_d, na.rm = T)
PFAS_X$bmi_mom_prepreg_d [is.na(PFAS_X$bmi_mom_prepreg_d)] <- 30
PFAS_X$smokpreg_final_d [is.na(PFAS_X$smokpreg_final_d)] <- "xnever"
PFAS_X$coll_grad [is.na(PFAS_X$coll_grad)] <- 0

##### Set missing values to the mean of nonmissing values for continuous variables
#PFAS_X$exer <- ifelse(is.na(PFAS_X$exer), mean(PFAS_X$exer,na.rm=F), PFAS_X$exer)
#PFAS_X$bmi <- ifelse(is.na(PFAS_X$bmi), mean(PFAS_X$bmi,na.rm=F), PFAS_X$bmi)
#PFAS_X$smoke <- ifelse(is.na(PFAS_X$smoke), mean(PFAS_X$smoke,na.rm=F), PFAS_X$smoke)
#PFAS_X$edu <- ifelse(is.na(PFAS_X$edu), mean(PFAS_X$edu,na.rm=F), PFAS_X$edu)

##### 1) Start with complete case model of conditional mean income
#m1 <- lm(exer ~ age + income  + bmi + edu + parity, data=PFASBP_W)
#PFASBP_W$exer_p <- predict(m1, type="response", newdata=PFASBP_W)
##### Replace missing dbp with predicted value
#PFASBP_W$exer <- ifelse(is.na(PFASBP_W$exer), PFASBP_W$exer_p, PFASBP_W$exer)

##### 1) Start with complete case model of conditional mean income
#m2 <- lm(income ~ age + exer + as.factor(race) + bmi + edu + as.factor(smoke) + parity, data=PFASBP_W)
#PFASBP_W$income_p <- predict(m2, type="response", newdata=PFASBP_W)
##### Replace missing dbp with predicted value
#PFASBP_W$income <- ifelse(is.na(PFASBP_W$income), PFASBP_W$income_p, PFASBP_W$income)


##### 1) Start with complete case model of conditional mean income
#m3 <- lm(bmi ~ age + exer + as.factor(race) + income + edu + as.factor(smoke) + parity, data=PFASBP_W)
#PFASBP_W$bmi_p <- predict(m3, type="response", newdata=PFASBP_W)
##### Replace missing dbp with predicted value
#PFASBP_W$bmi <- ifelse(is.na(PFASBP_W$bmi), PFASBP_W$bmi_p, PFASBP_W$bmi)

##### 1) Start with complete case model of conditional mean income
#m4 <- lm(smoke ~ age + exer + as.factor(race) + bmi + edu + income + parity, data=PFASBP_W)
#PFASBP_W$smoke_p <- predict(m4, type="response", newdata=PFASBP_W)
# Replace missing dbp with predicted value
#PFASBP_W$smoke <- ifelse(is.na(PFASBP_W$smoke), PFASBP_W$smoke_p, PFASBP_W$smoke)
```



```{r}
##### RENAME
PFAS_X$exer <- PFAS_X$mod_pre_d + PFAS_X$vig_pre_d
PFAS_X$race <- PFAS_X$race2_mom_epi_epia_d
PFAS_X$edu <- PFAS_X$coll_grad
PFAS_X$bmi <- PFAS_X$bmi_mom_prepreg_d
PFAS_X$smoke <- PFAS_X$smokpreg_final_d
PFAS_X$income <- PFAS_X$income_hh_epq_epqa_d
PFAS_X$parity <- PFAS_X$parity_d

##### RE-LABEL 
PFAS_X$race <- ifelse(PFAS_X$race == "white", 0,
                        ifelse(PFAS_X$race == "black", 1,
                        ifelse(PFAS_X$race == "hispa", 2,
                        ifelse(PFAS_X$race == "asian", 3,
                        ifelse(PFAS_X$race == "other", 4,
                        ifelse(PFAS_X$race == "more than 1 race", 5, 5))))))
PFAS_X$bmi <- ifelse(PFAS_X$bmi <25, 0, 1)
PFAS_X$smoke <- ifelse(PFAS_X$smoke == "former", 0,
                         ifelse(PFAS_X$smoke == "smoke preg", 1,
                         ifelse(PFAS_X$smoke == "xnever", 2, 2)))
PFAS_X$income <- ifelse(PFAS_X$income == 1, 0, 
                       ifelse(PFAS_X$income == 2, 0,
                       ifelse(PFAS_X$income == 3, 0,
                       ifelse(PFAS_X$income == 4, 0,
                       ifelse(PFAS_X$income == 5, 1,
                       ifelse(PFAS_X$income == 6, 2,0))))))
PFAS_X$parity <- ifelse(PFAS_X$parity == 0, 0,
                          ifelse(PFAS_X$parity > 0, 1, 0))

##### REFACTOR
PFAS_X$race <- factor(PFAS_X$race,
                        levels = c(0, 1, 2, 3, 4, 5),
                        labels = c("White", "Black", "Hispanic", "Asian", "Other", "More than 1 race"))

PFAS_X$edu <- factor(PFAS_X$edu,
                       levels = c(0, 1),
                       labels = c(" < college degree", ">= college degree"))
PFAS_X$bmi <- factor(PFAS_X$bmi,
                       levels = c(0, 1),
                       labels = c("< 25", ">= 25"))
PFAS_X$smoke <- factor(PFAS_X$smoke,
                         levels = c(0, 1, 2),
                         labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_X$income <- factor(PFAS_X$income,
                          levels = c(0, 1, 2),
                          labels = c("<= $40,000", "$40,001-$70,000", "> $70,000"))
PFAS_X$parity <- factor(PFAS_X$parity,
                          levels = c(0, 1),
                          labels = c("Nulliparous", "Parous"))

```



```{r}
##### DETERMINE PFAS MISSINGNESS
summary(PFAS_X$PFOS)
summary(PFAS_X$PFOA)
summary(PFAS_X$PFOSA)
summary(PFAS_X$PFNA2)
summary(PFAS_X$PFHxS)
summary(PFAS_X$PFDeA)
summary(PFAS_X$Me_PFOSA_AcOH2)
summary(PFAS_X$Et_PFOSA_AcOH)

##### EXCLUDE INELEGIBLE PARTICIPANTS
PFAS_1 <- subset(PFAS_X, !is.na(PFOS)) # MISSING PFAS DATA
PFAS_1 <- subset(PFAS_1, g_age_days_COLL_D_BLD1 <= 84) # MISSING 1ST TRIMESTER PFAS DATA

table(PFAS_1$highbp_mom_epi_epia_d)
PFAS_1 <- subset(PFAS_1, highbp_mom_epi_epia_d != 1) # HISTORY OF HYPERTENSION

table(PFAS_1$t1diab_mom_epi_epia_d)
table(PFAS_1$t2diab_mom_epi_epia_d)
PFAS_1 <- subset(PFAS_1, t1diab_mom_epi_epia_d != 1 & t2diab_mom_epi_epia_d != 1) # HISTORY OF DIABETES

table(PFAS_1$htn_rx_preg)
PFAS_5 <- subset(PFAS_1, htn_rx_preg !=1) # PAST/CURRENT USE OF BP MEDICATION

summary(PFAS_5)

```


```{r}
##### SAVE DATASET
write.csv(PFAS_5, file = "C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_5.csv", row.names = T)
write_sas(PFAS_5, "C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_5.sas7bdat")

```

