```{r}
##### LOAD PACKAGES
library("bkmr")
library("corrplot")
library("ggplot2")
library("beepr")

##### LOAD DATASET
PFAS_SYS <- read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_SYS_BKMR.csv")
PFAS_DIAS <- read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_DIAS_BKMR.csv")

```

```{r}
##### DESCRIBE LNPFAS DISTRIBUTION
hist(PFAS_SYS$a_sys)
hist(PFAS_DIAS$a_dias)

```

```{r}
##### SCALE LNPFAS MEASURES
PFAS_SYS$LNPFOS_Z <- scale(PFAS_SYS$LNPFOS)
PFAS_SYS$LNPFOA_Z <- scale(PFAS_SYS$LNPFOA)
PFAS_SYS$LNPFNA_Z <- scale(PFAS_SYS$LNPFNA2)
PFAS_SYS$LNPFHxS_Z <- scale(PFAS_SYS$LNPFHxS)
PFAS_SYS$LNME_PFOSA_Z <- scale(PFAS_SYS$LNME_PFOSA)
PFAS_SYS$LNET_PFOSA_Z <- scale(PFAS_SYS$LNET_PFOSA)

PFAS_DIAS$LNPFOS_Z <- scale(PFAS_DIAS$LNPFOS)
PFAS_DIAS$LNPFOA_Z <- scale(PFAS_DIAS$LNPFOA)
PFAS_DIAS$LNPFNA_Z <- scale(PFAS_DIAS$LNPFNA2)
PFAS_DIAS$LNPFHxS_Z <- scale(PFAS_DIAS$LNPFHxS)
PFAS_DIAS$LNME_PFOSA_Z <- scale(PFAS_DIAS$LNME_PFOSA)
PFAS_DIAS$LNET_PFOSA_Z <- scale(PFAS_DIAS$LNET_PFOSA)

```

```{r}
##### RENAME VARIABLES IN THE SYSTOLIC BP DATASET
PFAS_SYS$age <- PFAS_SYS$mom_agey_bp
PFAS_SYS$exer <- PFAS_SYS$mod_pre_d + PFAS_SYS$vig_pre_d
PFAS_SYS$edu <- PFAS_SYS$coll_grad
PFAS_SYS$bmi <- PFAS_SYS$bmi_mom_prepreg_d
PFAS_SYS$smoke <- PFAS_SYS$smokpreg_final_d
PFAS_SYS$income <- PFAS_SYS$income_hh_epq_epqa_d
PFAS_SYS$parity <- PFAS_SYS$parity_d
PFAS_SYS$race <- PFAS_SYS$race2_mom_epi_epia_d

# RELABEL 
PFAS_SYS$edu <- ifelse(PFAS_SYS$edu == 0, 1,
                         ifelse(PFAS_SYS$edu == 1, 0, 1))
PFAS_SYS$bmi_cat <- ifelse(PFAS_SYS$bmi <25, 0, 1)
PFAS_SYS$smoke <- ifelse(PFAS_SYS$smoke == "xnever", 0,
                         ifelse(PFAS_SYS$smoke == "former", 1,
                         ifelse(PFAS_SYS$smoke == "smoke preg", 2, 2)))
PFAS_SYS$income_cat <- ifelse(PFAS_SYS$income == 1, 2, 
                       ifelse(PFAS_SYS$income == 2, 2,
                       ifelse(PFAS_SYS$income == 3, 2,
                       ifelse(PFAS_SYS$income == 4, 2,
                       ifelse(PFAS_SYS$income == 5, 1,
                       ifelse(PFAS_SYS$income == 6, 0,2))))))
PFAS_SYS$parity <- ifelse(PFAS_SYS$parity == 0, 0,
                          ifelse(PFAS_SYS$parity > 0, 1, 0))
PFAS_SYS$race <- ifelse(PFAS_SYS$race == "white", 0,
                        ifelse(PFAS_SYS$race == "black", 1,
                        ifelse(PFAS_SYS$race == "hispa", 2,
                        ifelse(PFAS_SYS$race == "asian", 3,
                        ifelse(PFAS_SYS$race == "other", 4,
                        ifelse(PFAS_SYS$race == "more than 1 race", 5, 5))))))

# REFACTOR
#PFAS_SYS$race <- factor(PFAS_SYS$race,
#                        levels = c(0, 1, 2, 3, 4, 5),
#                        labels = c("White", "Black", "Hispanic", "Asian", "Other", "More than 1 race"))
#PFAS_SYS$edu <- factor(PFAS_SYS$edu,
#                       levels = c(0, 1),
#                       labels = c(">= college degree","< college degree"))
#PFAS_SYS$bmi <- factor(PFAS_SYS$bmi,
#                       levels = c(0, 1),
#                       labels = c("< 25", ">= 25"))
#PFAS_SYS$smoke <- factor(PFAS_SYS$smoke,
#                         levels = c(0, 1, 2),
#                         labels = c("Never smokes", "Smoked during pregnancy", "Former smoker"))
#PFAS_SYS$income <- factor(PFAS_SYS$income,
#                          levels = c(0, 1, 2),
#                          labels = c("> $70,000", "$40,001-$70,000", "<= $40,000"))
#PFAS_SYS$parity <- factor(PFAS_SYS$parity,
#                          levels = c(0, 1),
#                          labels = c("Nulliparous", "Parous"))

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_SYS$edu <- as.factor(PFAS_SYS$edu)
PFAS_SYS$smoke <- as.factor(PFAS_SYS$smoke)
PFAS_SYS$income_cat <- as.factor(PFAS_SYS$income_cat)
PFAS_SYS$parity <- as.factor(PFAS_SYS$parity)
PFAS_SYS$race <- as.factor(PFAS_SYS$race)

# CENTER AND SCALE CONTINUOUS VARIABLES
PFAS_SYS$age <- scale(PFAS_SYS$age)
PFAS_SYS$bmi <- scale(PFAS_SYS$bmi)
PFAS_SYS$exer <- scale(PFAS_SYS$exer)



##### RENAME VARIABLES IN THE DIASOLIC BP DATASET
PFAS_DIAS$age <- PFAS_DIAS$mom_agey_bp
PFAS_DIAS$exer <- PFAS_DIAS$mod_pre_d + PFAS_DIAS$vig_pre_d
PFAS_DIAS$edu <- PFAS_DIAS$coll_grad
PFAS_DIAS$bmi <- PFAS_DIAS$bmi_mom_prepreg_d
PFAS_DIAS$smoke <- PFAS_DIAS$smokpreg_final_d
PFAS_DIAS$income <- PFAS_DIAS$income_hh_epq_epqa_d
PFAS_DIAS$parity <- PFAS_DIAS$parity_d
PFAS_DIAS$race <- PFAS_DIAS$race2_mom_epi_epia_d

# RE-LABEL 
PFAS_DIAS$edu <- ifelse(PFAS_DIAS$edu == 0, 1,
                         ifelse(PFAS_DIAS$edu == 1, 0, 1))
PFAS_DIAS$bmi_cat <- ifelse(PFAS_DIAS$bmi <25, 0, 1)
PFAS_DIAS$smoke <- ifelse(PFAS_DIAS$smoke == "xnever", 0,
                         ifelse(PFAS_DIAS$smoke == "former", 1,
                         ifelse(PFAS_DIAS$smoke == "smoke preg", 2, 2)))
PFAS_DIAS$income_cat <- ifelse(PFAS_DIAS$income == 1, 2, 
                       ifelse(PFAS_DIAS$income == 2, 2,
                       ifelse(PFAS_DIAS$income == 3, 2,
                       ifelse(PFAS_DIAS$income == 4, 2,
                       ifelse(PFAS_DIAS$income == 5, 1,
                       ifelse(PFAS_DIAS$income == 6, 0,2))))))
PFAS_DIAS$parity <- ifelse(PFAS_DIAS$parity == 0, 0,
                          ifelse(PFAS_DIAS$parity > 0, 1, 0))
PFAS_DIAS$race <- ifelse(PFAS_DIAS$race == "white", 0,
                        ifelse(PFAS_DIAS$race == "black", 1,
                        ifelse(PFAS_DIAS$race == "hispa", 2,
                        ifelse(PFAS_DIAS$race == "asian", 3,
                        ifelse(PFAS_DIAS$race == "other", 4,
                        ifelse(PFAS_DIAS$race == "more than 1 race", 5, 5))))))

# REFACTOR
#PFAS_DIAS$race <- factor(PFAS_DIAS$race,
#                        levels = c(0, 1, 2, 3, 4, 5),
#                        labels = c("White", "Black", "Hispanic", "Asian", "Other", "More than 1 race"))
#PFAS_DIAS$edu <- factor(PFAS_DIAS$edu,
#                       levels = c(0, 1),
#                       labels = c(">= college degree","< college degree"))
#PFAS_DIAS$bmi <- factor(PFAS_DIAS$bmi,
#                       levels = c(0, 1),
#                       labels = c("< 25", ">= 25"))
#PFAS_DIAS$smoke <- factor(PFAS_DIAS$smoke,
#                         levels = c(0, 1, 2),
#                         labels = c("Never smokes", "Smoked during pregnancy", "Former smoker"))
#PFAS_DIAS$income <- factor(PFAS_DIAS$income,
#                          levels = c(0, 1, 2),
#                          labels = c("> $70,000", "$40,001-$70,000", "<= $40,000"))
#PFAS_DIAS$parity <- factor(PFAS_DIAS$parity,
#                          levels = c(0, 1),
#                          labels = c("Nulliparous", "Parous"))

# SET CATEGORICAL VARIABLES AS FACTORS
PFAS_DIAS$edu <- as.factor(PFAS_DIAS$edu)
PFAS_DIAS$smoke <- as.factor(PFAS_DIAS$smoke)
PFAS_DIAS$income_cat <- as.factor(PFAS_DIAS$income_cat)
PFAS_DIAS$parity <- as.factor(PFAS_DIAS$parity)
PFAS_DIAS$race <- as.factor(PFAS_DIAS$race)

# CENTER AND SCALE CONTINUOUS VARIABLES)
PFAS_DIAS$age <- scale(PFAS_DIAS$age)
PFAS_DIAS$bmi <- scale(PFAS_DIAS$bmi)
PFAS_DIAS$exer <- scale(PFAS_DIAS$exer)

```

```{r}
##### REORDER COLUMNS
#PFAS_SYS <- PFAS_SYS[, c(1:5, 7:10, 6, 11:17, 20:25, 18, 19, 26:32)]

#PFAS_DIAS <- PFAS_DIAS[, c(1:5, 7:10, 6, 11:17, 20:25, 18, 19, 26:32)]

```

```{r}
##### BKMR WITH LOG-TRANSFORMED PFAS #####
mixture_sys <- as.matrix(PFAS_SYS[,29:34]) # THESE PFASs ARE LOG-TRANSFORMED
mixture_dias <- as.matrix(PFAS_DIAS[,29:34]) # THESE PFASs ARE LOG-TRANSFORMED

a_sys <- PFAS_SYS$a_sys
c_sys <- PFAS_SYS$c_sys
a_dias <- PFAS_DIAS$a_dias
c_dias <- PFAS_DIAS$c_dias

cov_sys <- as.matrix(cbind(PFAS_SYS$age, PFAS_SYS$edu, PFAS_SYS$exer, PFAS_SYS$income_cat, PFAS_SYS$parity, PFAS_SYS$bmi, PFAS_SYS$race))
cov_dias <- as.matrix(cbind(PFAS_DIAS$age, PFAS_SYS$edu, PFAS_DIAS$exer, PFAS_DIAS$income_cat, PFAS_DIAS$parity, PFAS_DIAS$bmi, PFAS_DIAS$race))
cov_sys_nr <- as.matrix(cbind(PFAS_SYS$age, PFAS_DIAS$edu, PFAS_SYS$exer, PFAS_SYS$income_cat, PFAS_SYS$parity, PFAS_SYS$bmi))
cov_dias_nr <- as.matrix(cbind(PFAS_DIAS$age, PFAS_DIAS$edu, PFAS_DIAS$exer, PFAS_DIAS$income_cat, PFAS_DIAS$parity, PFAS_DIAS$bmi))

set.seed(10)
knots_sys <- fields::cover.design(mixture_sys, nd = 120)$design
knots_dias <- fields::cover.design(mixture_dias, nd = 120)$design

```

```{r}
##### BUILD BKMR MODELS FOR SYSTOLIC BLOOD PRESSURE
m11_a_sys <- kmbayes(y=a_sys, Z=mixture_sys, X=cov_sys, iter=25000, verbose=FALSE, varsel=TRUE, knots = knots_sys)
beep(sound=5, expr=NULL)
summary(m11_a_sys)
ExtractPIPs(m11_a_sys)

m12_a_sys <- kmbayes(y=a_sys, Z=mixture_sys, X=cov_sys_nr, iter=25000, verbose=FALSE, varsel=TRUE, knots = knots_sys)
beep(sound=5, expr=NULL)
summary(m12_a_sys)
ExtractPIPs(m12_a_sys)

m13_c_sys <- kmbayes(y=c_sys, Z=mixture_sys, X=cov_sys, iter=25000, verbose=FALSE, varsel=TRUE, knots = knots_sys)
beep(sound=5, expr=NULL)
summary(m13_c_sys)
ExtractPIPs(m13_c_sys)

m14_c_sys <- kmbayes(y=c_sys, Z=mixture_sys, X=cov_sys_nr, iter=25000, verbose=FALSE, varsel=TRUE, knots = knots_sys)
beep(sound=5, expr=NULL)
summary(m14_c_sys)
ExtractPIPs(m14_c_sys)

```

```{r}
##### VALUES TO KEEP AFTER BURIN/THIN
#
sel <- seq(0,25000,by = 50)

##### ACCESS CONVERGENCE WITH TRACEPLOTS
TracePlot(fit = m11_a_sys, par = "beta", sel = sel)
TracePlot(fit = m12_a_sys, par = "beta", sel = sel)
TracePlot(fit = m13_c_sys, par = "beta", sel = sel)
TracePlot(fit = m14_c_sys, par = "beta", sel = sel)


##### VALUES TO KEEP AFTER BURNING/THIN (ACCORDING TO THE TRACEPLOT FUNCTION ABOVE)
sel_m11_a_sys <- seq(5001, 25000, 50)
TracePlot(fit = m11_a_sys, par = "beta", sel = sel_m11_a_sys)
TracePlot(fit = m11_a_sys, par = "sigsq.eps", sel = sel_m11_a_sys)

sel_m12_a_sys <- seq(5001, 25000, 50)
TracePlot(fit = m12_a_sys, par = "beta", sel = sel_m12_a_sys)
TracePlot(fit = m12_a_sys, par = "sigsq.eps", sel = sel_m12_a_sys)

sel_m13_c_sys <- seq(5001, 25000, 50)
TracePlot(fit = m13_c_sys, par = "beta", sel = sel_m13_c_sys)
TracePlot(fit = m13_c_sys, par = "sigsq.eps", sel = sel_m13_c_sys)

sel_m14_c_sys <- seq(5001, 25000, 50)
TracePlot(fit = m14_c_sys, par = "beta", sel = sel_m14_c_sys)
TracePlot(fit = m14_c_sys, par = "sigsq.eps", sel = sel_m14_c_sys)

```

```{r}
##### PREDICT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
pred_univar_m11_a_sys <- PredictorResponseUnivar(fit = m11_a_sys, sel = sel_m11_a_sys, method = "approx")
pred_univar_m11_a_sys

pred_univar_m12_a_sys <- PredictorResponseUnivar(fit = m12_a_sys, sel = sel_m12_a_sys, method = "approx")
pred_univar_m12_a_sys

pred_univar_m13_c_sys <- PredictorResponseUnivar(fit = m13_c_sys, sel = sel_m13_c_sys, method = "approx")
pred_univar_m13_c_sys

pred_univar_m14_c_sys <- PredictorResponseUnivar(fit = m14_c_sys, sel = sel_m14_c_sys, method = "approx")
pred_univar_m14_c_sys


##### PLOT UNIVARIATE EXPOSURE-RESPONSE FUNCTION
m1 <- ggplot(pred_univar_m11_a_sys, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("h(z)") + facet_wrap(~ variable)
m1

m2 <- ggplot(pred_univar_m12_a_sys, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("h(z)") + facet_wrap(~ variable)
m2

m3 <- ggplot(pred_univar_m13_c_sys, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("h(z)") + facet_wrap(~ variable)
m3

m4 <- ggplot(pred_univar_m14_c_sys, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) +
  geom_smooth(stat = "identity") + ylab("h(z)") + facet_wrap(~ variable)
m4

```

```{r}
##### PREDICT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
pred_bivar_m11_a_sys <- PredictorResponseBivar(fit = m11_a_sys, min.plot.dist = 1, sel = sel_m11_a_sys, method = "approx")
pred_interact_m11_a_sys <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_m11_a_sys, Z = mixture_sys,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_m11_a_sys

pred_bivar_m12_a_sys <- PredictorResponseBivar(fit = m12_a_sys, min.plot.dist = 1, sel = sel_m12_a_sys, method = "approx")
pred_interact_m12_a_sys <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_m12_a_sys, Z = mixture_sys,
                                                        both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_m12_a_sys


pred_bivar_m13_c_sys <- PredictorResponseBivar(fit = m13_c_sys, min.plot.dist = 1, sel = sel_m13_c_sys, method = "approx")
pred_interact_m13_c_sys <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_m13_c_sys, Z = mixture_sys, both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_m13_c_sys


pred_bivar_m14_c_sys <- PredictorResponseBivar(fit = m14_c_sys, min.plot.dist = 1, sel = sel_m14_c_sys, method = "approx")
pred_interact_m14_c_sys <- PredictorResponseBivarLevels(pred.resp.df = pred_bivar_m14_c_sys, Z = mixture_sys, both_pairs = T, qs = c(0.25, 0.50, 0.75))
pred_interact_m14_c_sys

##### PLOT INTERACTIONS BETWEEN EXPOSURE AND RESPONSE
m11 <- ggplot(pred_interact_m11_a_sys, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | quantiles of PFAS2)") 
m11


m22 <- ggplot(pred_interact_m12_a_sys, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | quantiles of PFAS2)") 
m22


m33 <- ggplot(pred_interact_m13_c_sys, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | quantiles of PFAS2)") 
m33


m44 <- ggplot(pred_interact_m14_c_sys, aes(z1, est)) +
  geom_smooth(aes(col = quantile), stat = "identity") + 
  facet_grid(variable2 ~ variable1) +
  xlab ("PFAS1") +
  ggtitle("h(PFAS1 | quantiles of PFAS2)") 
m44

```

```{r}
##### DETERMINE RISK ASSOCIATED WITH THE OVERALL MIXTURE
risk_overall_m11_a_sys <- OverallRiskSummaries(fit = m11_a_sys, q.fixed = 0.50, sel = sel_m11_a_sys,method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risk_overall_m11_a_sys

risk_overall_m12_a_sys <- OverallRiskSummaries(fit = m12_a_sys, q.fixed = 0.50, sel = sel_m12_a_sys, method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risk_overall_m12_a_sys

risk_overall_m13_c_sys <- OverallRiskSummaries(fit = m13_c_sys, q.fixed = 0.50, sel = sel_m13_c_sys, method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risk_overall_m13_c_sys

risk_overall_m14_c_sys <- OverallRiskSummaries(fit = m14_c_sys, q.fixed = 0.50, sel = sel_m14_c_sys, method = "approx", qs = seq(0.25, 0.75, by = 0.05))
risk_overall_m14_c_sys

##### PLOT RISK ASSOCIATED WITH THE OVERALL MIXTURE
m111 <- ggplot(risk_overall_m11_a_sys, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "estimate")
m111

m222 <- ggplot(risk_overall_m12_a_sys, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "estimate")
m222

m333 <- ggplot(risk_overall_m13_c_sys, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "estimate")
m333


m444 <- ggplot(risk_overall_m14_c_sys, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) +
               geom_hline(yintercept = 00, linetype = "dashed", color = "dark blue") +
               geom_pointrange() +
               scale_y_continuous(name = "estimate")
m444

```

