```{r}
##### LOAD PACKAGES
library("dplyr")
library("tidyverse")
library("plyr")
library("htmlTable")
library("table1")
library("gtools")

##### LOAD DATASET
PFAS_W <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_W.csv")

```

```{r}
##### COUNT BP MEASURES
summary(PFAS_W$count.1)
hist(PFAS_W$count.1)

##### GESTATIONAL AGE AT 1ST BP MEASURE
summary(PFAS_W$ga_days.1)
hist(PFAS_W$ga_days.1)

##### MATERNAL AGE AT 1ST BP MEASURE
summary(PFAS_W$age)
hist(PFAS_W$age)

##### SYSTOLIC BP AT 1ST BP MEASURE
summary(PFAS_W$sys.1)
hist(PFAS_W$sys.1)
boxplot(PFAS_W$sys.1)

##### DIASTOLIC AT 1ST BP MEASURE
summary(PFAS_W$dias.1)
hist(PFAS_W$dias.1)
boxplot(PFAS_W$dias.1)

##### DESCRIBE PFAS DISTRIBUTION
hist(PFAS_W$PFOS)
hist(PFAS_W$PFOA)
#hist(PFAS_W$PFOSA)
hist(PFAS_W$PFNA2)
hist(PFAS_W$PFHxS)
#hist(PFAS_W$PFDeA)
hist(PFAS_W$Me_PFOSA_AcOH2)
hist(PFAS_W$Et_PFOSA_AcOH)

##### DESCRIBE LNPFAS DISTRIBUTION
hist(PFAS_W$LNPFOS)
hist(PFAS_W$LNPFOA)
#hist(PFAS_W$LNPFOSA)
hist(PFAS_W$LNPFNA2)
hist(PFAS_W$LNPFHxS)
#hist(PFAS_W$LNPFDeA)
hist(PFAS_W$LNME_PFOSA)
hist(PFAS_W$LNET_PFOSA)


```

```{r}
PFAS_W$exer <- PFAS_W$mod_pre_d + PFAS_W$vig_pre_d
PFAS_W$race <- PFAS_W$race2_mom_epi_epia_d
PFAS_W$edu <- PFAS_W$coll_grad
PFAS_W$bmi <- PFAS_W$bmi_mom_prepreg_d
PFAS_W$smoke <- PFAS_W$smokpreg_final_d
PFAS_W$income <- PFAS_W$income_hh_epq_epqa_d
PFAS_W$parity <- PFAS_W$parity_d

##### RE-LABEL 
PFAS_W$race <- ifelse(PFAS_W$race == "white", 0,
                        ifelse(PFAS_W$race == "black", 1,
                        ifelse(PFAS_W$race == "hispa", 2,
                        ifelse(PFAS_W$race == "asian", 3,
                        ifelse(PFAS_W$race == "other", 4,
                        ifelse(PFAS_W$race == "more than 1 race", 5, 5))))))
PFAS_W$bmi <- ifelse(PFAS_W$bmi <25, 0, 1)
PFAS_W$smoke <- ifelse(PFAS_W$smoke == "former", 0,
                         ifelse(PFAS_W$smoke == "smoke preg", 1,
                         ifelse(PFAS_W$smoke == "xnever", 2, 2)))
PFAS_W$income <- ifelse(PFAS_W$income == 1, 0, 
                       ifelse(PFAS_W$income == 2, 0,
                       ifelse(PFAS_W$income == 3, 0,
                       ifelse(PFAS_W$income == 4, 0,
                       ifelse(PFAS_W$income == 5, 1,
                       ifelse(PFAS_W$income == 6, 2,0))))))
PFAS_W$parity <- ifelse(PFAS_W$parity == 0, 0,
                          ifelse(PFAS_W$parity > 0, 1, 0))

##### REFACTOR
PFAS_W$race <- factor(PFAS_W$race,
                        levels = c(0, 1, 2, 3, 4, 5),
                        labels = c("White", "Black", "Hispanic", "Asian", "Other", "More than 1 race"))

PFAS_W$edu <- factor(PFAS_W$edu,
                       levels = c(0, 1),
                       labels = c(" < college degree", ">= college degree"))
PFAS_W$bmi <- factor(PFAS_W$bmi,
                       levels = c(0, 1),
                       labels = c("< 25", ">= 25"))
PFAS_W$smoke <- factor(PFAS_W$smoke,
                         levels = c(0, 1, 2),
                         labels = c("Former smoker", "Smoked during pregnancy", "Never smoked"))
PFAS_W$income <- factor(PFAS_W$income,
                          levels = c(0, 1, 2),
                          labels = c("<= $40,000", "$40,001-$70,000", "> $70,000"))
PFAS_W$parity <- factor(PFAS_W$parity,
                          levels = c(0, 1),
                          labels = c("Nulliparous", "Parous"))


##### LABEL
label(PFAS_W$age) <- "Maternal age at 1st BP measure"
label(PFAS_W$ga_days.1) <- "Gestational age at 1st BP measure"
label(PFAS_W$exer) <- "Physical activity"
label(PFAS_W$race) <- "Race/Ethnicity"
label(PFAS_W$edu) <- "Education"
label(PFAS_W$bmi) <- "Pre-pregnancy BMI"
label(PFAS_W$smoke) <- "Smoking status"
label(PFAS_W$income) <- "Annual household income"
label(PFAS_W$parity) <- "Parity"

##### ADD UNITS
units(PFAS_W$age)  <- "years"
units(PFAS_W$ga_days.1)  <- "weeks"
units(PFAS_W$bmi)  <- "kg/m2"
units(PFAS_W$exer) <- "hrs/week"

##### TABE 1
table1(~ age + ga_days.1 + exer + race + bmi + edu + smoke + income + parity, data = PFAS_W, overall="Total")

table(PFAS_W$smokpreg_final_d)
table(PFAS_W$education_mom_epi_epia_d)
summary(PFAS_W$bmi)
table(PFAS_W$vig)
table(PFAS_W$parity_d)
half <- PFAS_W$age < 35
summary(half)


```

```{r}
##### TABLE 1 BY PCA #####

##### CREATE QUARTILES OF PRINCIPAL COMPONENTS
PFAS_W$PC1Q <- quantcut(PFAS_W$PC1, q = 4, na.rm = T)
PFAS_W$PC2Q <- quantcut(PFAS_W$PC2, q = 4, na.rm = T)
PFAS_W$PC3Q <- quantcut(PFAS_W$PC3, q = 4, na.rm = T)

##### TABE 1
table1(~ age + ga_days.1 + exer + race + bmi + edu + smoke + income + parity | PC1Q, data = PFAS_W, overall="Total")

```


```{r}
##### SAVE DATASET
write.csv(PFAS_W, file = "C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_W.csv", row.names = T)

```
