
```{r}
##### LOAD PACKAGES
library("nlme")
library("lme4")
library("lmerTest")
library("Rcpp")
library("ggplot2")
library("gtools")
library("sitar")
library("gamlss")
library("haven")
library("foreign")
library("fdapace")
library("hbgd")
library("dplyr")
library("ggpubr")
library("growthstandards")

##### LOAD DATASET
PFAS <-read.csv("C:/Users/jarva/Desktop/James-Todd Lab/PFASandBP/Data/PFAS_L.csv")

```

```{r}
##### CREATE QUARTILES OF PFAS
PFAS$PFOAQ <- quantcut(PFAS$PFOA, q = 4, na.rm = T)
PFAS$PFOSQ <- quantcut(PFAS$PFOS, q = 4, na.rm = T)
PFAS$PFNAQ <- quantcut(PFAS$PFNA2, q = 4, na.rm = T)
PFAS$PFHxSQ <- quantcut(PFAS$PFHxS, q = 4, na.rm = T)
PFAS$ETPFQ <- quantcut(PFAS$Et_PFOSA_AcOH, q = 4, na.rm = T)
PFAS$MEPFQ <- quantcut(PFAS$Me_PFOSA_AcOH2, q = 4, na.rm = T)

##### SUBSET DATA BY PFOA QUARTILE
summary(PFAS$PFOAQ)
PFAS_PFOA1 <- subset(PFAS, PFAS$PFOA <= 4.3)
PFAS_PFOA2 <- subset(PFAS, PFAS$PFOA > 4.3 & PFAS$PFOA <= 6.0)
PFAS_PFOA3 <- subset(PFAS, PFAS$PFOA > 6.0 & PFAS$PFOA <= 8.0)
PFAS_PFOA4 <- subset(PFAS, PFAS$PFOA > 8.0)

##### SUBSET DATA BY PFOS QUARTILE
summary(PFAS$PFOSQ)
PFAS_PFOS1 <- subset(PFAS, PFAS$PFOS <= 19.2)
PFAS_PFOS2 <- subset(PFAS, PFAS$PFOS > 19.2 & PFAS$PFOS <= 26.1)
PFAS_PFOS3 <- subset(PFAS, PFAS$PFOS > 26.1 & PFAS$PFOS <= 35.6)
PFAS_PFOS4 <- subset(PFAS, PFAS$PFOS > 35.6)

##### SUBSET DATA BY PFNA2 QUARTILE
summary(PFAS$PFNAQ)
PFAS_PFNA1 <- subset(PFAS, PFAS$PFNA2 <= 0.0707)
PFAS_PFNA2 <- subset(PFAS, PFAS$PFNA2 > 0.0707 & PFAS$PFNA2 <= 0.5)
PFAS_PFNA3 <- subset(PFAS, PFAS$PFNA2 > 0.5 & PFAS$PFNA2 <= 0.7)
PFAS_PFNA4 <- subset(PFAS, PFAS$PFNA2 > 0.7)

##### SUBSET DATA BY PFHxS QUARTILE
summary(PFAS$PFHxSQ)
PFAS_PFHxS1 <- subset(PFAS, PFAS$PFHxS <= 0.0707)
PFAS_PFHxS2 <- subset(PFAS, PFAS$PFHxS > 0.0707 & PFAS$PFHxS <= 1.7)
PFAS_PFHxS3 <- subset(PFAS, PFAS$PFHxS > 1.7 & PFAS$PFHxS <= 2.5)
PFAS_PFHxS4 <- subset(PFAS, PFAS$PFHxS > 2.5)

##### SUBSET DATA BY Et_PFOSA_AcOH QUARTILE
summary(PFAS$ETPFQ)
PFAS_ETPF1 <- subset(PFAS, PFAS$Et_PFOSA_AcOH <= 0.0707)
PFAS_ETPF2 <- subset(PFAS, PFAS$Et_PFOSA_AcOH > 0.0707 & PFAS$Et_PFOSA_AcOH <= 0.8)
PFAS_ETPF3 <- subset(PFAS, PFAS$Et_PFOSA_AcOH > 0.8 & PFAS$Et_PFOSA_AcOH <= 1.2)
PFAS_ETPF4 <- subset(PFAS, PFAS$Et_PFOSA_AcOH > 1.9)

##### SUBSET DATA BY Me_PFOSA_AcOH2 QUARTILE
summary(PFAS$MEPFQ)
PFAS_MEPF1 <- subset(PFAS, PFAS$Me_PFOSA_AcOH2 <= 0.1)
PFAS_MEPF2 <- subset(PFAS, PFAS$Me_PFOSA_AcOH2 > 0.1 & PFAS$Me_PFOSA_AcOH2 <= 1.3)
PFAS_MEPF3 <- subset(PFAS, PFAS$Me_PFOSA_AcOH2 > 1.3 & PFAS$Me_PFOSA_AcOH2 <= 3.2)
PFAS_MEPF4 <- subset(PFAS, PFAS$Me_PFOSA_AcOH2 > 3.2)

```


```{r}
##### FIT RANDOM INTERCEPTS MODEL FOR PFOA
m10 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)
m11 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOA1)
m12 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOA2)
m13 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOA3)
m14 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOA4)


##### RANDOM INTERCEPTS PLOT FOR PFOA
PFAS$m10_int <- predict(m10)
PFAS_PFOA1$m11_int <- predict(m11)
PFAS_PFOA2$m12_int <- predict(m12)
PFAS_PFOA3$m13_int <- predict(m13)
PFAS_PFOA4$m14_int <- predict(m14)

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = m10_int), alpha = 0.5) +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOA)")

ggplot(PFAS_PFOA1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = m11_int), alpha = 0.5, color = "red3") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOA, Q1)")

ggplot(PFAS_PFOA2, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = m12_int), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOA, Q2)")

ggplot(PFAS_PFOA3, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = m13_int), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOA, Q3)")

ggplot(PFAS_PFOA4, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = m14_int), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOA, Q4)")

```


```{r}
##### FIT RANDOM INTERCEPTS MODEL FOR PFOS
m20 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)
m21 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOS1)
m22 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOS2)
m23 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOS3)
m24 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFOS4)


##### RANDOM INTERCEPTS PLOT FOR PFOS
PFAS$m20_int <- predict(m20)
PFAS_PFOS1$m21_int <- predict(m21)
PFAS_PFOS2$m22_int <- predict(m22)
PFAS_PFOS3$m23_int <- predict(m23)
PFAS_PFOS4$m24_int <- predict(m24)

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
  geom_line(aes(y = m20_int), alpha = 0.5) +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOS)")

ggplot(PFAS_PFOS1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
  geom_line(aes(y = m21_int), alpha = 0.5, color = "red3") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOS, Q1)")

ggplot(PFAS_PFOS2, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
  geom_line(aes(y = m22_int), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOS, Q2)")

ggplot(PFAS_PFOS3, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
  geom_line(aes(y = m23_int), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOS, Q3)")

ggplot(PFAS_PFOS4, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = m24_int), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFOS, Q4)")

```



```{r}
##### FIT RANDOM INTERCEPTS MODEL FOR PFNA
m30 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)
#m31 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
#             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFNA1)
m32 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFNA2)
m33 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFNA3)
m34 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFNA4)


##### RANDOM INTERCEPTS PLOT FOR PFNA
PFAS$m30_int <- predict(m30)
#PFAS_PFOS1$m31_int <- predict(m31)
PFAS_PFNA2$m32_int <- predict(m32)
PFAS_PFNA3$m33_int <- predict(m33)
PFAS_PFNA4$m34_int <- predict(m34)

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFNAQ))) +
  geom_line(aes(y = m30_int), alpha = 0.5) +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFNA)")

#ggplot(PFAS_PFOS1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
#  geom_line(aes(y = m31_int), alpha = 0.5, color = "red3") +
# xlim(NA, 300) +
#  ylim(NA, 160) +
#  xlab("Gestational Age (Days)") + 
#  ylab("Systolic Blood Pressure") + 
#  ggtitle("Random-intercepts Model (PFNA, Q1)")

ggplot(PFAS_PFNA2, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFNAQ))) +
  geom_line(aes(y = m32_int), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFNA, Q2)")

ggplot(PFAS_PFNA3, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFNAQ))) +
  geom_line(aes(y = m33_int), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFNA, Q3)")

ggplot(PFAS_PFNA4, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFNAQ))) +
  geom_line(aes(y = m34_int), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFNA, Q4)")
```


```{r}
##### FIT RANDOM INTERCEPTS MODEL FOR PFHxS
m40 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)
#m41 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
#             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFHxS1)
m42 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFHxS2)
m43 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFHxS3)
m44 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_PFHxS4)


##### RANDOM INTERCEPTS PLOT FOR PFHxS
PFAS$m40_int <- predict(m40)
#PFAS_PFHxS1$m41_int <- predict(m41)
PFAS_PFHxS2$m42_int <- predict(m42)
PFAS_PFHxS3$m43_int <- predict(m43)
PFAS_PFHxS4$m44_int <- predict(m44)

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
  geom_line(aes(y = m40_int), alpha = 0.5) +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFHxS)")

#ggplot(PFAS_PFHxS1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFHxSQ))) +
#  geom_line(aes(y = m41_int), alpha = 0.5, color = "red3") +
#  xlim(NA, 300) +
#  ylim(NA, 160) +
#  xlab("Gestational Age (Days)") + 
#  ylab("Systolic Blood Pressure") + 
#  ggtitle("Random-intercepts Model (PFHxS, Q1)")

ggplot(PFAS_PFHxS2, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFHxSQ))) +
  geom_line(aes(y = m42_int), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFHxS, Q2)")

ggplot(PFAS_PFHxS3, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFHxSQ))) +
  geom_line(aes(y = m43_int), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFHxS, Q3)")

ggplot(PFAS_PFHxS4, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFHxSQ))) +
  geom_line(aes(y = m44_int), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (PFHxS, Q4)")
```


```{r}
##### FIT RANDOM INTERCEPTS MODEL FOR EtFOSAA
m50 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)
#m51 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
#             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_ETPF1)
m52 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_ETPF2)
m53 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_ETPF3)
m54 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_ETPF4)


##### RANDOM INTERCEPTS PLOT FOR EtFOSAA
PFAS$m50_int <- predict(m50)
#PFAS_ETPF1$m51_int <- predict(m51)
PFAS_ETPF2$m52_int <- predict(m52)
PFAS_ETPF3$m53_int <- predict(m53)
PFAS_ETPF4$m54_int <- predict(m54)

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(ETPFQ))) +
  geom_line(aes(y = m50_int), alpha = 0.5) +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (EtFOSAA)")

#ggplot(PFAS_ETPF1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(ETPFQ))) +
#  geom_line(aes(y = m51_int), alpha = 0.5, color = "red3") +
#  xlim(NA, 300) +
#  ylim(NA, 160) +
#  xlab("Gestational Age (Days)") + 
#  ylab("Systolic Blood Pressure") + 
#  ggtitle("Random-intercepts Model (EtFOSAA, Q1)")

ggplot(PFAS_ETPF2, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(ETPFQ))) +
  geom_line(aes(y = m52_int), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (EtFOSAA, Q2)")

ggplot(PFAS_ETPF3, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(ETPFQ))) +
  geom_line(aes(y = m53_int), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (EtFOSAA, Q3)")

ggplot(PFAS_ETPF4, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(ETPFQ))) +
  geom_line(aes(y = m54_int), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (EtFOSAA, Q4)")

```




```{r}
##### FIT RANDOM INTERCEPTS MODEL FOR MeFOSSA
m60 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)
#m61 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
#             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_MEPF1)
m62 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_MEPF2)
m63 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_MEPF3)
m64 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS_MEPF4)


##### RANDOM INTERCEPTS PLOT FOR MeFOSSA
PFAS$m60_int <- predict(m60)
#PFAS_MEPF1$m61_int <- predict(m61)
PFAS_MEPF2$m62_int <- predict(m62)
PFAS_MEPF3$m63_int <- predict(m63)
PFAS_MEPF4$m64_int <- predict(m64)

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(MEPFQ))) +
  geom_line(aes(y = m60_int), alpha = 0.5) +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (MeFOSSA)")

#ggplot(PFAS_MEPF1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(MEPFQ))) +
#  geom_line(aes(y = m61_int), alpha = 0.5, color = "red3") +
#  xlim(NA, 300) +
#  ylim(NA, 160) +
#  xlab("Gestational Age (Days)") + 
#  ylab("Systolic Blood Pressure") + 
#  ggtitle("Random-intercepts Model (MeFOSSA, Q1)")

ggplot(PFAS_MEPF2, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(MEPFQ))) +
  geom_line(aes(y = m62_int), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (MeFOSSA, Q2)")

ggplot(PFAS_MEPF3, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(MEPFQ))) +
  geom_line(aes(y = m63_int), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (MeFOSSA, Q3)")

ggplot(PFAS_MEPF4, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFHxSQ))) +
  geom_line(aes(y = m64_int), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts Model (MeFOSSA, Q4)")
```

















```{r}
##### FIT RANDOM INTERCEPTS MODEL
mod1 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 | aid), data = PFAS)


##### RANDOM INTERCEPTS PLOT
PFAS$lmer_int1 <- predict(mod1)



ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int1), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")









ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int2), alpha = 0.5, color = "red3") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS_PFOA2, aes(x = ga_days, y = sys, group = factor(aid), color = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int2), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS_PFOA3, aes(x = ga_days, y = sys, group = factor(aid), color = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int2), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS_PFOA4, aes(x = ga_days, y = sys, group = factor(aid), color = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int2), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")



```



```{r}
##### FIT RANDOM INTERCEPTS MODEL
mod2 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 + ga_days | aid), data = PFAS_PFOA1, REML = FALSE)

numcols <- grep("^c\\.",names(PFAS))
dfs <- PFAS
dfs[,numcols] <- scale(dfs[,numcols])
m1_sc <- update(m1,data=dfs)




mod2_1 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (ga_days | aid), data = PFAS_PFOA1)


mod2_2 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (ga_days | aid), data = PFAS_PFOA2)


mod2_3 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (ga_days | aid), data = PFAS_PFOA3)


mod2_4 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (ga_days | aid), data = PFAS_PFOA4)



##### RANDOM INTERCEPTS PLOT
PFAS$lmer_int2 <- predict(mod2)
PFAS_PFOA1$lmer_int21 <- predict(mod2_1)
PFAS_PFOA2$lmer_int22 <- predict(mod2_2)
PFAS_PFOA3$lmer_int23 <- predict(mod2_3)
PFAS_PFOA4$lmer_int24 <- predict(mod2_4)


ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int2), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")





ggplot(PFAS_PFOA1, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int21), alpha = 0.5, color = "red3") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS_PFOA2, aes(x = ga_days, y = sys, group = factor(aid), color = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int22), alpha = 0.5, color = "forestgreen") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS_PFOA3, aes(x = ga_days, y = sys, group = factor(aid), color = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int23), alpha = 0.5, color = "darkturquoise") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS_PFOA4, aes(x = ga_days, y = sys, group = factor(aid), color = factor(PFOAQ))) +
  geom_line(aes(y = lmer_int24), alpha = 0.5, color = "darkorchid4") +
  xlim(NA, 300) +
  ylim(NA, 160) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")
```

```{r}
MOD_1 <- lmer(sys ~ ga_days + mom_agey_bp + exer + as.factor(race) + bmi 
             + as.factor(edu) + as.factor(smoke) + as.factor(income) + parity + (1 + ga_days | aid), data = PFAS_ETPF4, REML = FALSE)

```



```{r}
gplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFOSQ))) +
  geom_line(aes(y = lmer_int), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFNAQ))) +
  geom_line(aes(y = lmer_int), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(PFHxSQ))) +
  geom_line(aes(y = lmer_int), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(ETPFQ))) +
  geom_line(aes(y = lmer_int), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")

ggplot(PFAS, aes(x = ga_days, y = sys, group = factor(aid), colour = factor(MEPFQ))) +
  geom_line(aes(y = lmer_int), alpha = 0.5) +
  xlab("Gestational Age (Days)") + 
  ylab("Systolic Blood Pressure") + 
  ggtitle("Random-intercepts")
```

